name: Continuous Integration

on:
  push:
    branches: [ master ]
    
    paths:
      - src/**
      - prisma/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Dependencies install 
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Digital Ocean | Copy app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          source: >
            ., 
            !node_modules,
            !src,
            !.vscode,
            !.github,
            !.git,
            !.gitignore,
            !.editorconfig,
            !.env.example,
            !.eslintignore,
            !.eslintrc.json,
            !prettier.config.js,
            !babel.config.js,
            !tsconfig.json,
            !README.md
          target: "~/app"
          
      - name: Digital Ocean | Dependencies install | Migrations | Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          script: |
            cd ~/app 
            npm install
            npx prisma migrate deploy
            pm2 restart ${{ secrets.APP_TESTNET_ID }}
